name: Votemarket analytics
on:
  push:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: CRV analytics
        id: crv
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://votemarket.stakedao.org/api/analytics/global?protocolKey=crv"
          timeout: 600000
      - name: BAL Analytics
        id: bal
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://votemarket.stakedao.org/api/analytics/global?protocolKey=bal"
          timeout: 600000
      - name: FXS analytics
        id: fxs
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://votemarket.stakedao.org/api/analytics/global?protocolKey=fxs"
          timeout: 600000
      - name: ANGLE Analytics
        id: angle
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://votemarket.stakedao.org/api/analytics/global?protocolKey=angle"
          timeout: 600000
      - name: Overwrite CRV file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: analytics/crv.json
          write-mode: overwrite
          contents: |
            ${{ steps.crv.outputs.response }}
      - name: Overwrite BAL file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: analytics/bal.json
          write-mode: overwrite
          contents: |
            ${{ steps.bal.outputs.response }}
      - name: Overwrite FXS file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: analytics/fxs.json
          write-mode: overwrite
          contents: |
            ${{ steps.fxs.outputs.response }}
      - name: Overwrite ANGLE file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: analytics/angle.json
          write-mode: overwrite
          contents: |
            ${{ steps.angle.outputs.response }}
      - run: |
          git config --local user.email "pierre@stakedao.org"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Add changes"
          git push